// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ Missions — weekly, personal install-anchored challenge set.                ║
// ║ Design: Docs/MISSIONS_PLAN.md.                                             ║
// ║                                                                            ║
// ║ A "week" is a personal 7-day window living in save.week. It starts when    ║
// ║ the previous week's rewards are collected (or at first init), freezes to a ║
// ║ "finished" state when every mission is done OR the timer expires, and only ║
// ║ advances to a fresh week when the player taps COLLECT. Counters are weekly ║
// ║ and reset each cycle. Reward XP is granted via ph_grant_xp(...,false) so a  ║
// ║ level-crossing routes through the Level-Up screen.                         ║
// ║                                                                            ║
// ║ PHASE 1 SCOPE: the data/cycle engine + the catalog + the solve-driven      ║
// ║ counters (total / per-puzzle / prev-day / daily-goals / perfect-days).     ║
// ║ Counters that need their own event hooks (bonus words, no-hint, speed,     ║
// ║ Wordle ≤3 / win-streak) are reserved in the stats struct but no live       ║
// ║ mission depends on them yet — see the DEFERRED note in the catalog.        ║
// ╚══════════════════════════════════════════════════════════════════════════╝

// ── Puzzle roster (drives per-puzzle parameterized missions) ──────────────────
/// The 10 puzzle keys, matching the win-screen claim_key prefixes
/// ("<puzzle>_<date>") and the "solved_<puzzle>" weekly stat keys.
function ph_mission_puzzles() {
    static _list = ["anygram","sudoku","wordwave","shikaku","wordle",
                    "huesort","colorlink","wordbend","arrows","ladder"];
    return _list;
}

/// Player-facing display name for a puzzle key.
function ph_mission_puzzle_name(_key) {
    switch (_key) {
        case "anygram":   return "Anygram";
        case "sudoku":    return "Sudoku";
        case "wordwave":  return "Word Wave";
        case "shikaku":   return "Shikaku";
        case "wordle":    return "Wordle";
        case "huesort":   return "Hue Sort";
        case "colorlink": return "Color Link";
        case "wordbend":  return "Word Bend";
        case "arrows":    return "Arrows";
        case "ladder":    return "Ladder";
    }
    return _key;
}

/// Icon sprite-key (filename base) for a puzzle key — resolved to a loaded
/// sprite by the Profile UI.
function ph_mission_puzzle_icon(_key) {
    return "game_" + _key;
}

// ── Mission definition builder (YYC-safe: empty literal + assignment) ─────────
/// A catalog entry. metric = key into the weekly stats (or a computed metric:
/// "distinct_types", "types_ge3"). title may contain "{target}".
function ph_mission_def(_id, _band, _metric, _target, _reward, _title, _icon) {
    var _d = {};
    _d.id     = _id;
    _d.band   = _band;       // "quick" | "core" | "challenge"
    _d.metric = _metric;
    _d.target = _target;
    _d.reward = _reward;
    _d.title  = _title;
    _d.icon   = _icon;       // sprite-key (filename base)
    return _d;
}

// ── Catalog (cached) ──────────────────────────────────────────────────────────
/// Returns the full pool of mission definitions. Built once and cached on
/// global.__ph_mission_catalog. Per-puzzle missions are generated by looping the
/// roster, so this short authored list expands into many concrete missions.
function ph_mission_catalog() {
    if (variable_global_exists("__ph_mission_catalog")) return global.__ph_mission_catalog;

    var _c  = [];
    var _ps = ph_mission_puzzles();
    var _i;

    // ── QUICK (reward 50) — front-loaded, clearable in 1–2 sessions ───────────
    array_push(_c, ph_mission_def("warm_up",   "quick", "solved_total",   3, PH_MISSION_XP_QUICK, "Solve {target} puzzles",             "icon_trophy3d"));
    array_push(_c, ph_mission_def("sampler",    "quick", "distinct_types", 3, PH_MISSION_XP_QUICK, "Play {target} different puzzle types","icon_puzzle"));
    array_push(_c, ph_mission_def("first_goal", "quick", "daily_goals",    1, PH_MISSION_XP_QUICK, "Reach the Daily Goal once",          "icon_gift"));
    array_push(_c, ph_mission_def("on_the_board","quick","solved_wordle",  1, PH_MISSION_XP_QUICK, "Win {target} Wordle",                "game_wordle"));
    array_push(_c, ph_mission_def("word_spotter","quick","bonus_words",    5, PH_MISSION_XP_QUICK, "Find {target} bonus words",          "icon_chest"));
    // Try-it: solve 1 of a specific puzzle (one per puzzle) — teaches the roster.
    for (_i = 0; _i < array_length(_ps); _i++) {
        var _p = _ps[_i];
        array_push(_c, ph_mission_def("try_" + _p, "quick", "solved_" + _p, 1, PH_MISSION_XP_QUICK,
            "Solve a " + ph_mission_puzzle_name(_p) + " puzzle", ph_mission_puzzle_icon(_p)));
    }

    // ── CORE (150–300) — a few days of normal play ────────────────────────────
    array_push(_c, ph_mission_def("double_digits",  "core", "solved_total",     10, PH_MISSION_XP_CORE_LOW,  "Solve {target} puzzles",                  "icon_trophy3d"));
    array_push(_c, ph_mission_def("puzzle_run",      "core", "solved_total",     25, PH_MISSION_XP_CORE_HIGH, "Solve {target} puzzles",                  "icon_trophy3d"));
    array_push(_c, ph_mission_def("goal_getter",     "core", "daily_goals",       3, PH_MISSION_XP_CORE_LOW,  "Reach the Daily Goal on {target} days",   "icon_gift"));
    array_push(_c, ph_mission_def("wordle_streaker", "core", "solved_wordle",     3, PH_MISSION_XP_CORE_LOW,  "Win {target} Wordles",                    "game_wordle"));
    array_push(_c, ph_mission_def("time_traveler",   "core", "prev_day_solves",  10, PH_MISSION_XP_CORE_HIGH, "Solve {target} puzzles from past days",   "icon_calendar"));
    array_push(_c, ph_mission_def("bonus_hunter",     "core", "bonus_words",      25, PH_MISSION_XP_CORE_LOW,  "Find {target} bonus words",               "icon_chest"));
    array_push(_c, ph_mission_def("wordbend_wordsmith","core","bonus_words_5",     5, PH_MISSION_XP_CORE_HIGH, "Find {target} five-letter bonus words",   "game_wordbend"));
    array_push(_c, ph_mission_def("big_word",         "core", "bonus_words_6plus", 3, PH_MISSION_XP_CORE_HIGH, "Find {target} six-letter+ bonus words",   "game_wordbend"));
    array_push(_c, ph_mission_def("speedster",        "core", "speed_solves",      5, PH_MISSION_XP_CORE_LOW,  "Solve {target} puzzles under 90s",        "icon_stopwatch"));
    array_push(_c, ph_mission_def("sharpshooter",     "core", "wordle_wins_le3",   2, PH_MISSION_XP_CORE_HIGH, "Win {target} Wordles in 3 guesses or fewer","game_wordle"));
    array_push(_c, ph_mission_def("purist",           "core", "hintless_solves",  15, PH_MISSION_XP_CORE_HIGH, "Solve {target} puzzles without a hint",   "icon_bulb"));
    // Type specialist: solve 5 of a specific puzzle (one per puzzle).
    for (_i = 0; _i < array_length(_ps); _i++) {
        var _p2 = _ps[_i];
        array_push(_c, ph_mission_def("type_specialist_" + _p2, "core", "solved_" + _p2, 5, PH_MISSION_XP_CORE_HIGH,
            "Solve {target} " + ph_mission_puzzle_name(_p2) + " puzzles", ph_mission_puzzle_icon(_p2)));
    }

    // ── CHALLENGE (450) — the pacers; intended to take most of the week ───────
    array_push(_c, ph_mission_def("centurion",     "challenge", "solved_total",  100, PH_MISSION_XP_CHALLENGE, "Solve {target} puzzles",                "icon_trophy3d"));
    array_push(_c, ph_mission_def("daily_devotee",  "challenge", "daily_goals",    7, PH_MISSION_XP_CHALLENGE, "Reach the Daily Goal on {target} days", "icon_gift"));
    array_push(_c, ph_mission_def("perfectionist",  "challenge", "perfect_days",   3, PH_MISSION_XP_CHALLENGE, "Get {target} Perfect Days (10/10)",     "icon_trophy3d"));
    array_push(_c, ph_mission_def("type_master",    "challenge", "types_ge3",     10, PH_MISSION_XP_CHALLENGE, "Solve every puzzle type 3+ times",      "icon_puzzle"));
    array_push(_c, ph_mission_def("flawless",       "challenge", "wordle_win_best", 5, PH_MISSION_XP_CHALLENGE, "Win {target} Wordles in a row (no miss)","game_wordle"));

    // STILL DEFERRED (needs per-day distinct-type tracking, not just weekly totals):
    //   hat_trick — "solve 3 different puzzle types in a single day, on N days".
    // Its counter isn't in ph_week_new_stats yet; add a per-day tracker before
    // activating. Everything else above is live as of Phase 2.

    global.__ph_mission_catalog = _c;
    return _c;
}

/// All catalog ids in a given band.
function ph_mission_ids_in_band(_band) {
    var _c = ph_mission_catalog();
    var _out = [];
    for (var _i = 0; _i < array_length(_c); _i++) {
        if (_c[_i].band == _band) array_push(_out, _c[_i].id);
    }
    return _out;
}

/// Look up a catalog definition by id (or undefined).
function ph_mission_find_def(_id) {
    var _c = ph_mission_catalog();
    for (var _i = 0; _i < array_length(_c); _i++) {
        if (_c[_i].id == _id) return _c[_i];
    }
    return undefined;
}

// ── Weekly stats ──────────────────────────────────────────────────────────────
/// Fresh weekly counter struct (all zero). Reset every cycle.
function ph_week_new_stats() {
    var _s = {};
    _s.solved_total    = 0;
    _s.prev_day_solves = 0;
    _s.daily_goals     = 0;   // count of days that crossed 4 solves this week
    _s.perfect_days    = 0;   // count of days that reached 10 solves this week
    // per-puzzle solve counts
    var _ps = ph_mission_puzzles();
    for (var _i = 0; _i < array_length(_ps); _i++) {
        _s[$ "solved_" + _ps[_i]] = 0;
    }
    // reserved (deferred hooks) — present so future missions work additively
    _s.bonus_words       = 0;
    _s.bonus_words_5     = 0;
    _s.bonus_words_6plus = 0;
    _s.speed_solves      = 0;
    _s.hintless_solves   = 0;
    _s.wordle_wins_le3   = 0;
    _s.wordle_win_run    = 0;   // current consecutive Wordle wins this week
    _s.wordle_win_best   = 0;   // best run this week (the "Flawless" metric)
    return _s;
}

// ── Generic counter bump + event recorders (Phase 2 hooks) ────────────────────
/// Add `_n` to a weekly counter (creating it if missing). No-op while finished.
/// Does NOT write the save — callers persist as part of their own flow.
function ph_week_bump(_save, _metric, _n) {
    ph_week_init(_save);
    if (_save.week.status != "active") return;
    var _st = _save.week.stats;
    if (!variable_struct_exists(_st, _metric)) _st[$ _metric] = 0;
    _st[$ _metric] += _n;
}

/// A bonus word was found (Anygram / Word Bend). Bumps the total + length buckets.
function ph_week_record_bonus_word(_save, _word) {
    ph_week_bump(_save, "bonus_words", 1);
    var _len = string_length(_word);
    if (_len == 5) ph_week_bump(_save, "bonus_words_5", 1);
    if (_len >= 6) ph_week_bump(_save, "bonus_words_6plus", 1);
}

/// Flag that a hint was used on a given puzzle-date (claim_key). Read by the
/// solve hook so a hinted solve doesn't count toward "no-hint" missions.
function ph_week_mark_hint_used(_save, _key) {
    if (_key == "") return;
    if (!variable_struct_exists(_save, "hint_used")) _save.hint_used = {};
    _save.hint_used[$ _key] = true;
}

function ph_week_hint_used(_save, _key) {
    return variable_struct_exists(_save, "hint_used")
        && variable_struct_exists(_save.hint_used, _key)
        && _save.hint_used[$ _key];
}

/// A Wordle was missed — reset the running win streak (the best stays banked).
function ph_week_record_wordle_miss(_save) {
    ph_week_init(_save);
    if (_save.week.status != "active") return;
    _save.week.stats.wordle_win_run = 0;
}

/// Resolve a metric value from a stats struct, incl. computed metrics.
function ph_week_metric(_stats, _metric) {
    if (_metric == "distinct_types" || _metric == "types_ge3") {
        var _ps  = ph_mission_puzzles();
        var _min = (_metric == "types_ge3") ? 3 : 1;
        var _n   = 0;
        for (var _i = 0; _i < array_length(_ps); _i++) {
            var _k = "solved_" + _ps[_i];
            if (variable_struct_exists(_stats, _k) && _stats[$ _k] >= _min) _n++;
        }
        return _n;
    }
    return variable_struct_exists(_stats, _metric) ? _stats[$ _metric] : 0;
}

// ── Mission instances (what's stored in save.week.missions) ───────────────────
/// Build a live mission instance from a catalog def (YYC-safe).
function ph_mission_instance(_def) {
    var _m = {};
    _m.id      = _def.id;
    _m.band    = _def.band;
    _m.metric  = _def.metric;
    _m.target  = _def.target;
    _m.reward  = _def.reward;
    _m.title   = _def.title;
    _m.icon    = _def.icon;
    _m.claimed = false;
    return _m;
}

/// Current raw counter value behind a mission.
function ph_mission_value(_save, _m) {
    return ph_week_metric(_save.week.stats, _m.metric);
}

/// Progress clamped to the target (for the bar / "x / N" label).
function ph_mission_progress(_save, _m) {
    return min(ph_mission_value(_save, _m), _m.target);
}

/// Display title with {target} substituted.
function ph_mission_title(_m) {
    return string_replace_all(_m.title, "{target}", string(_m.target));
}

function ph_mission_is_complete(_save, _m) {
    return ph_mission_value(_save, _m) >= _m.target;
}

/// Claimable = complete and not yet claimed. Allowed during the active week AND
/// the finished ("Week Complete") state, where the player claims rewards in-page
/// (individually or via CLAIM ALL) before the next week rolls in.
function ph_mission_claimable(_save, _m) {
    var _st = _save.week.status;
    return (_st == "active" || _st == "finished") && !_m.claimed && ph_mission_is_complete(_save, _m);
}

/// Claim a single mission's reward (per-mission CLAIM during the active week).
/// Grants XP via ph_grant_xp(...,false); a level-crossing queues the Level-Up
/// screen (reward < 500 so at most one boundary). Returns
/// { ok, reward, levels_gained, new_level }.
function ph_mission_claim(_save, _m) {
    if (!ph_mission_claimable(_save, _m)) {
        return { ok:false, reward:0, levels_gained:0, new_level:ph_level_from_xp(_save.xp) };
    }
    _m.claimed = true;
    var _res = ph_grant_xp(_save, _m.reward, false);
    if (_res.levels_gained > 0) {
        global.pending_levelup = { level:_res.new_level, base_reward:PH_COINS_PER_LEVEL };
    }
    ph_save_write(_save);
    return { ok:true, reward:_m.reward, levels_gained:_res.levels_gained, new_level:_res.new_level };
}

// ── Week-level queries ────────────────────────────────────────────────────────
function ph_week_all_complete(_save) {
    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        if (!ph_mission_is_complete(_save, _ms[_i])) return false;
    }
    return true;
}

function ph_week_all_claimed(_save) {
    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        if (!_ms[_i].claimed) return false;
    }
    return true;
}

/// How many missions are currently claimable (drives the Profile-tab badge).
function ph_week_claimable_count(_save) {
    if (!variable_struct_exists(_save, "week")) return 0;
    var _n = 0;
    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        if (ph_mission_claimable(_save, _ms[_i])) _n++;
    }
    return _n;
}

function ph_week_has_claimable(_save) {
    return ph_week_claimable_count(_save) > 0;
}

/// Whole days remaining (for the "Reset in N Days" pill). 0 once expired.
function ph_week_days_left(_save) {
    var _elapsed = date_current_datetime() - _save.week.start_dt;   // in days (real)
    return max(0, ceil(PH_WEEK_LENGTH_DAYS - _elapsed));
}

function ph_week_expired(_save) {
    return (date_current_datetime() - _save.week.start_dt) >= PH_WEEK_LENGTH_DAYS;
}

/// Compact countdown to the weekly reset, e.g. "2d 12h" (≥1 day),
/// "12h 30m" (<1 day) or "5m" (<1 hour). "0m" once expired. Used by the
/// Event Hub header timer pill.
function ph_week_time_left_str(_save) {
    var _rem_days = PH_WEEK_LENGTH_DAYS - (date_current_datetime() - _save.week.start_dt);
    if (_rem_days <= 0) return "0m";
    var _total_min = floor(_rem_days * 24 * 60);
    var _d = _total_min div (24 * 60);
    var _h = (_total_min div 60) mod 24;
    var _m = _total_min mod 60;
    if (_d > 0) return string(_d) + "d " + string(_h) + "h";
    if (_h > 0) return string(_h) + "h " + string(_m) + "m";
    return string(_m) + "m";
}

// ── Draw ──────────────────────────────────────────────────────────────────────
/// Pick `_count` ids from a band, preferring ids not used within the last
/// PH_WEEK_DRAW_COOLDOWN weeks (save.week.recent: id -> week index last used).
/// Degrades gracefully (relaxes the cooldown) if a band is short on fresh ids.
function ph_week_pick_band(_save, _band, _count) {
    var _ids    = ph_mission_ids_in_band(_band);
    var _recent = variable_struct_exists(_save.week, "recent") ? _save.week.recent : {};
    var _idx    = _save.week.index;

    var _fresh = [];
    var _used  = [];
    for (var _i = 0; _i < array_length(_ids); _i++) {
        var _id = _ids[_i];
        var _last = variable_struct_exists(_recent, _id) ? _recent[$ _id] : -9999;
        if ((_idx - _last) > PH_WEEK_DRAW_COOLDOWN) array_push(_fresh, _id);
        else array_push(_used, _id);
    }
    _fresh = ph_array_shuffle(_fresh);
    _used  = ph_array_shuffle(_used);
    var _pool = array_concat(_fresh, _used);   // fresh first, then relax cooldown

    var _out = [];
    for (var _j = 0; _j < _count && _j < array_length(_pool); _j++) array_push(_out, _pool[_j]);
    return _out;
}

/// Fisher-Yates on a COPY (does not mutate the input).
function ph_array_shuffle(_arr) {
    var _a = array_create(array_length(_arr));
    array_copy(_a, 0, _arr, 0, array_length(_arr));
    for (var _i = array_length(_a) - 1; _i > 0; _i--) {
        var _j = irandom(_i);
        var _t = _a[_i]; _a[_i] = _a[_j]; _a[_j] = _t;
    }
    return _a;
}

/// Build this week's mission instance array from a list of ids.
function ph_week_build_missions(_ids) {
    var _out = [];
    for (var _i = 0; _i < array_length(_ids); _i++) {
        var _def = ph_mission_find_def(_ids[_i]);
        if (!is_undefined(_def)) array_push(_out, ph_mission_instance(_def));
    }
    return _out;
}

/// Hand-authored Week 1: front-loaded, mostly Quick, no brutal Challenge.
function ph_week1_ids() {
    return [
        // Quick — includes Word Spotter (bonus words)
        "warm_up","sampler","first_goal","on_the_board","word_spotter",
        "try_anygram","try_sudoku","try_wordwave","try_wordle",
        "try_shikaku","try_huesort","try_colorlink","try_wordbend",
        // Core — gentle ramp + Speedster
        "double_digits","puzzle_run","goal_getter","wordle_streaker","time_traveler",
        "speedster",
        "type_specialist_anygram","type_specialist_sudoku","type_specialist_wordle"
    ];
}

/// Random draw for week ≥ 2 (per §4 band composition).
function ph_week_draw(_save) {
    var _ids = [];
    _ids = array_concat(_ids, ph_week_pick_band(_save, "quick",     PH_WEEK_QUICK_COUNT));
    _ids = array_concat(_ids, ph_week_pick_band(_save, "core",      PH_WEEK_CORE_COUNT));
    _ids = array_concat(_ids, ph_week_pick_band(_save, "challenge", PH_WEEK_CHALLENGE_COUNT));
    return ph_week_build_missions(_ids);
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────
/// Ensure save.week exists. Idempotent — no-op if a week is already present.
/// Week 1 uses the hand-authored set; later weeks come from ph_week_draw.
/// Forward-compat: ensure save.week.stats has every counter the current build
/// expects. Saves created by an earlier build are missing newer fields, so add
/// any with a 0 default rather than crashing when they're read.
function ph_week_ensure_stats(_save) {
    if (!variable_struct_exists(_save, "week")) return;
    if (!variable_struct_exists(_save.week, "stats") || !is_struct(_save.week.stats)) {
        _save.week.stats = ph_week_new_stats();
        return;
    }
    var _fresh = ph_week_new_stats();
    var _names = variable_struct_get_names(_fresh);
    for (var _i = 0; _i < array_length(_names); _i++) {
        var _k = _names[_i];
        if (!variable_struct_exists(_save.week.stats, _k)) _save.week.stats[$ _k] = 0;
    }
}

function ph_week_init(_save) {
    if (variable_struct_exists(_save, "week")
        && is_struct(_save.week)
        && variable_struct_exists(_save.week, "missions")) {
        ph_week_ensure_stats(_save);   // backfill any counters added since this save was made
        return;
    }
    var _w = {};
    _w.index    = 1;
    _w.status   = "active";
    _w.start_dt = date_current_datetime();
    _w.stats    = ph_week_new_stats();
    _w.bonus_claimed = false;
    _w.recent   = {};
    _save.week  = _w;
    _save.week.missions = ph_week_build_missions(ph_week1_ids());
}

/// Flip an active week to "finished" when every mission is complete OR the timer
/// expires. Call on save load and on entering the Profile screen. No grants here.
function ph_week_check_finish(_save) {
    if (!variable_struct_exists(_save, "week")) { ph_week_init(_save); return; }
    if (_save.week.status != "active") return;
    if (ph_week_all_complete(_save) || ph_week_expired(_save)) {
        _save.week.status = "finished";
        ph_save_write(_save);
    }
}

/// CLAIM ALL: grant every currently-claimable mission's reward at once (used by
/// the Week-Complete screen's "CLAIM ALL" button and the simultaneous star burst).
/// Does NOT grant the week bonus or advance the week — the caller runs
/// ph_week_collect after the celebration to finalize (bonus + roll over).
/// A level crossing queues the Level-Up screen via global.pending_levelup.
/// Returns { indices, xp_total, leveled }.
function ph_week_claim_all(_save) {
    var _idxs = [];
    var _xp_total = 0;
    var _leveled  = false;
    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        var _m = _ms[_i];
        if (!_m.claimed && ph_mission_is_complete(_save, _m)) {
            _m.claimed = true;
            var _r = ph_grant_xp(_save, _m.reward, false);
            _xp_total += _m.reward;
            if (_r.levels_gained > 0) _leveled = true;
            array_push(_idxs, _i);
        }
    }
    if (_leveled) {
        global.pending_levelup = { level:ph_level_from_xp(_save.xp), base_reward:PH_COINS_PER_LEVEL };
    }
    ph_save_write(_save);
    return { indices:_idxs, xp_total:_xp_total, leveled:_leveled };
}

/// COLLECT: grant any complete-but-unclaimed mission rewards + the week-complete
/// bonus (only if the full set was cleared), then advance to a fresh week.
/// Triggered only by the player's COLLECT tap. Returns a summary for the UI:
/// { xp_total, leveled, full_clear }.
function ph_week_collect(_save) {
    if (!variable_struct_exists(_save, "week") || _save.week.status != "finished") {
        return { xp_total:0, leveled:false, full_clear:false };
    }
    var _xp_total = 0;
    var _leveled  = false;
    var _full     = ph_week_all_complete(_save);

    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        var _m = _ms[_i];
        if (!_m.claimed && ph_mission_is_complete(_save, _m)) {
            _m.claimed = true;
            var _r = ph_grant_xp(_save, _m.reward, false);
            _xp_total += _m.reward;
            if (_r.levels_gained > 0) _leveled = true;
        }
    }
    if (_full && !_save.week.bonus_claimed) {
        _save.week.bonus_claimed = true;
        var _rb = ph_grant_xp(_save, PH_WEEK_COMPLETE_BONUS, false);
        _xp_total += PH_WEEK_COMPLETE_BONUS;
        if (_rb.levels_gained > 0) _leveled = true;
    }
    if (_leveled) {
        global.pending_levelup = { level:ph_level_from_xp(_save.xp), base_reward:PH_COINS_PER_LEVEL };
    }
    ph_week_advance(_save);
    ph_save_write(_save);
    return { xp_total:_xp_total, leveled:_leveled, full_clear:_full };
}

/// Roll into a fresh week: record this set's ids into the cooldown map, bump the
/// index, reset the timer + stats, and draw a new set.
function ph_week_advance(_save) {
    var _old_idx = _save.week.index;
    var _recent  = variable_struct_exists(_save.week, "recent") ? _save.week.recent : {};
    var _ms = _save.week.missions;
    for (var _i = 0; _i < array_length(_ms); _i++) {
        _recent[$ _ms[_i].id] = _old_idx;
    }
    _save.week.index        = _old_idx + 1;
    _save.week.status       = "active";
    _save.week.start_dt     = date_current_datetime();
    _save.week.stats        = ph_week_new_stats();
    _save.week.bonus_claimed = false;
    _save.week.recent       = _recent;
    _save.week.missions     = ph_week_draw(_save);
}

// ── Counter hook (called from ph_win_grant — the central XP claim point) ──────
/// Record one genuine puzzle solve into the current week's counters.
/// _claim_key = "<puzzle>_<YYYY-MM-DD>" (the win-screen claim key). Fires exactly
/// once per solve (ph_win_grant's `granted` guard). Does NOT write the save —
/// ph_win_grant writes once afterward.
function ph_week_record_solve(_save, _claim_key) {
    ph_week_init(_save);                         // defensive (brand-new save)
    if (_save.week.status != "active") return;   // ignore solves during a finished week

    var _len  = string_length(_claim_key);
    if (_len < 12) return;                        // need "<p>_YYYY-MM-DD"
    var _date = string_copy(_claim_key, _len - 9, 10);   // trailing YYYY-MM-DD
    var _puz  = string_copy(_claim_key, 1, _len - 11);   // everything before "_<date>"

    var _stats = _save.week.stats;
    _stats.solved_total += 1;
    var _pk = "solved_" + _puz;
    if (variable_struct_exists(_stats, _pk)) _stats[$ _pk] += 1;

    // back-catalog (Time Traveler): solving a puzzle dated before today
    if (ph_date_compare_keys(_date, ph_today_key()) < 0) _stats.prev_day_solves += 1;

    // daily-goal / perfect-day crossings for the solved date (count once each).
    // The done-flag is already set by *_check_win before the claim, so the count
    // includes this solve.
    var _c = ph_solved_count_on(_save, _date);
    if (_c == (PH_GIFT_PUZZLE_INDEX + 1)) _stats.daily_goals  += 1;   // crossed 4/10
    if (_c == PH_PUZZLES_PER_DAY)         _stats.perfect_days += 1;   // reached 10/10

    // No-hint solve (Purist): the hint flow flags save.hint_used[claim_key].
    if (!ph_week_hint_used(_save, _claim_key)) _stats.hintless_solves += 1;

    // Speed solve (Speedster): the active play-timer for this puzzle-date shares
    // the claim_key shape, so ph_timer_get gives whole seconds of play.
    var _secs = ph_timer_get(_save, _claim_key);
    if (_secs > 0 && _secs < PH_MISSION_SPEED_SECS) _stats.speed_solves += 1;

    // Wordle-specific: guesses-to-win (Sharpshooter) + win streak (Flawless).
    if (_puz == "wordle") {
        var _wst = ph_wordle_load_state(_save, _date);
        if (!is_undefined(_wst)) {
            var _ng = array_length(ph_wordle_guesses_from_str(_wst.guesses));
            if (_ng > 0 && _ng <= 3) _stats.wordle_wins_le3 += 1;
        }
        _stats.wordle_win_run += 1;
        _stats.wordle_win_best = max(_stats.wordle_win_best, _stats.wordle_win_run);
    }
}
